from: '"#{sitename} Support" <contact@#{domain}>'
subject: Password Reset from #{sitename}
content: |
  You receive this mail because there is a password reset request for the account using this email in #{sitename}. If you didn't ask for password reset, please just ignore this mail.

  To reset your password, click following link:

  [https://#{domain}/auth/passwd/reset/#{token}](https://#{domain}/auth/passwd/reset/#{token})

  Thanks,
  #{sitename} team
